# Generated by Django 2.2.12 on 2020-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('name', models.TextField(blank=True, help_text='Name for user', null=True, verbose_name='name')),
                ('email', models.EmailField(blank=True, help_text='I stand out in that an e-mail is stored', max_length=254, unique=True, verbose_name='email address')),
                ('age', models.IntegerField(default=0, help_text='Age of users', verbose_name='age')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
