# Generated by Django 2.2.12 on 2020-04-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('reference', models.TextField(help_text='number reference', unique=True, verbose_name='reference')),
                ('account', models.TextField(help_text='I stand out in that an e-mail is stored', verbose_name='account')),
                ('date', models.DateField(help_text='Date transaction', verbose_name='Date')),
                ('amount', models.IntegerField(help_text='Amount', verbose_name='Amount')),
                ('type_transaction', models.IntegerField(choices=[(10, 'inflow'), (20, 'outflow')], help_text='Type transaction', verbose_name='status about me')),
                ('category', models.TextField(help_text='Category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete='cascade', related_name='transactions', to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
